'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check, Menu, X } from 'lucide-react'
import { useState } from 'react'

const programs = [
  ['01', 'FIRST SPIN', 'Grip, stance, rules and basic control.', 'New to the game'],
  ['02', 'BUILD YOUR GAME', 'Footwork, consistency, placement and rally skills.', 'Developing players'],
  ['03', 'PERFORMANCE SQUAD', 'Tactical awareness, match play and structured training.', 'Advanced players'],
  ['04', 'PRIVATE COACHING', 'One-to-one sessions shaped around individual goals.', 'By enquiry'],
]
const principles = [['01', 'FOOTWORK', 'Get into position with balance and intention.'], ['02', 'CONTROL', 'Build reliable touch, height and placement.'], ['03', 'TIMING', 'Read the ball and find the right moment.'], ['04', 'MATCH IQ', 'Make better decisions under pressure.']]
const schedule = [['Beginner Fundamentals', 'Weekdays', 'Evening', 'New to the game'], ['Developing Players', 'Weekdays', 'Evening', 'Building consistency'], ['Performance Training', 'Selected days', 'Evening', 'Advanced'], ['Private Coaching', 'By enquiry', 'Flexible', 'Individual goals']]

function Mark({ dark = false }: { dark?: boolean }) { return <span className={`inline-flex size-7 items-center justify-center rounded-full border-2 ${dark ? 'border-[#F5F4EF]' : 'border-[#111214]'}`}><span className="size-2.5 rounded-full bg-[#D6FF3F]" /></span> }
function ButtonLink({ href, children, lime = false }: { href: string; children: React.ReactNode; lime?: boolean }) { return <Link href={href} className={`group inline-flex items-center gap-3 px-5 py-3 text-xs font-bold tracking-[0.16em] transition-transform hover:-translate-y-0.5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#D6FF3F] ${lime ? 'bg-[#D6FF3F] text-[#111214]' : 'bg-[#244BFF] text-white'}`}>{children}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link> }
function Label({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`mb-5 flex items-center gap-3 text-[10px] font-bold tracking-[0.22em] ${light ? 'text-[#D6FF3F]' : 'text-[#244BFF]'}`}><span className="size-2 bg-current" />{children}</p> }

export default function SpinpointHome() {
  const [menuOpen, setMenuOpen] = useState(false)
  const close = () => setMenuOpen(false)
  return <div className="overflow-hidden bg-[#F5F4EF] text-[#111214]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#111214]/95 text-[#F5F4EF] backdrop-blur-sm"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-10"><Link href="#top" className="flex items-center gap-3" onClick={close}><Mark dark /><span className="text-xl font-black tracking-[-0.06em]">SPINPOINT</span><span className="hidden border-l border-white/30 pl-3 text-[9px] tracking-[0.18em] text-[#A4A6AA] sm:block">TABLE TENNIS ACADEMY</span></Link><nav className="hidden items-center gap-7 text-[10px] font-bold tracking-[0.16em] lg:flex"><Link href="#academy">ACADEMY</Link><Link href="#programs">PROGRAMS</Link><Link href="#schedule">SCHEDULE</Link><Link href="#contact">CONTACT</Link></nav><div className="flex items-center gap-3"><Link href="/trial" className="hidden bg-[#D6FF3F] px-4 py-2.5 text-[10px] font-black tracking-[0.14em] text-[#111214] sm:block">BOOK A TRIAL</Link><button aria-label={menuOpen ? 'Close menu' : 'Open menu'} className="p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></div>{menuOpen && <nav className="flex flex-col gap-5 border-t border-white/10 bg-[#111214] px-5 py-6 text-sm font-bold tracking-[0.12em] lg:hidden"><Link href="#academy" onClick={close}>ACADEMY</Link><Link href="#programs" onClick={close}>PROGRAMS</Link><Link href="#schedule" onClick={close}>SCHEDULE</Link><Link href="#contact" onClick={close}>CONTACT</Link><Link href="/trial" className="w-fit bg-[#D6FF3F] px-4 py-3 text-[#111214]">BOOK A FREE TRIAL</Link></nav>}</header>
    <main id="top">
      <section className="relative flex min-h-[720px] items-end bg-[#111214] pt-24 text-[#F5F4EF] lg:min-h-[820px]"><div className="absolute inset-0 opacity-80"><Image src="/images/spinpoint-hero.png" alt="Table tennis player reaching for a shot" fill priority className="object-cover object-center lg:object-[58%_center]" /></div><div className="absolute inset-0 bg-gradient-to-r from-[#111214] via-[#111214]/75 to-transparent" /><div className="relative mx-auto grid w-full max-w-[1440px] px-5 pb-16 lg:px-10 lg:pb-24"><div><p className="mb-7 text-[10px] font-bold tracking-[0.28em] text-[#D6FF3F]">SP / 01 &nbsp; TRAIN / COMPETE / IMPROVE</p><h1 className="max-w-4xl text-[18vw] font-black uppercase leading-[0.82] tracking-[-0.08em] sm:text-[130px] lg:text-[150px]">Own the<br /><span className="text-[#D6FF3F]">next point.</span></h1><p className="mt-8 max-w-md text-base leading-relaxed text-[#D7D7D2]">Train with purpose. Play with confidence. Structured coaching for beginners, developing players and athletes ready to compete.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/trial" lime>BOOK A FREE TRIAL</ButtonLink><ButtonLink href="#programs">EXPLORE PROGRAMS</ButtonLink></div></div></div></section>
      <section id="academy" className="mx-auto grid max-w-[1440px] gap-12 px-5 py-24 lg:grid-cols-[0.9fr_1.1fr] lg:px-10 lg:py-36"><div className="relative min-h-[360px] lg:min-h-[530px]"><Image src="/images/spinpoint-detail.png" alt="Paddle, ball and table tennis net close up" fill className="object-cover" /><div className="absolute -bottom-6 -right-4 bg-[#244BFF] px-5 py-4 text-[10px] font-bold tracking-[0.18em] text-white">FOOTWORK / CONTROL / TIMING</div></div><div className="flex flex-col justify-center lg:pl-12"><Label>MORE THAN A PLACE TO PLAY</Label><h2 className="max-w-xl text-6xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-8xl">Every rally<br /><span className="text-[#244BFF]">starts somewhere.</span></h2><p className="mt-8 max-w-lg text-lg leading-relaxed text-[#5E6064]">Good players are built in the details. SpinPoint is a focused, welcoming space to learn fundamentals, build consistency and find confidence.</p></div></section>
      <section id="programs" className="bg-[#111214] px-5 py-24 text-[#F5F4EF] lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px] grid gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><Label light>FIND YOUR GAME</Label><h2 className="max-w-sm text-6xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-8xl">A program<br /><span className="text-[#D6FF3F]">for every stage.</span></h2></div><div className="border-t border-white/20">{programs.map(([number, name, desc, level]) => <div key={name} className="group grid grid-cols-[50px_1fr] gap-4 border-b border-white/20 py-7 md:grid-cols-[75px_1fr_180px_110px] md:items-center"><span className="text-2xl font-black text-[#D6FF3F]">{number}</span><div><h3 className="text-2xl font-black tracking-[-0.03em] group-hover:text-[#D6FF3F]">{name}</h3><p className="mt-2 max-w-md text-sm leading-relaxed text-[#A4A6AA]">{desc}</p></div><span className="hidden text-[10px] font-bold uppercase tracking-[0.14em] text-[#A4A6AA] md:block">{level}</span><Link href="/trial" className="col-start-2 mt-2 flex items-center gap-2 text-[10px] font-bold tracking-[0.15em] text-[#D6FF3F] md:col-start-auto md:mt-0">EXPLORE <ArrowRight className="size-4" /></Link></div>)}</div></div></section>
      <section className="bg-[#244BFF] px-5 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.3fr_0.7fr] lg:items-end"><div><Label light>THE NEXT POINT / START HERE</Label><h2 className="max-w-4xl text-6xl font-black uppercase leading-[0.84] tracking-[-0.07em] sm:text-8xl lg:text-[120px]">Your first point<br /><span className="text-[#D6FF3F]">starts here.</span></h2></div><div><p className="max-w-sm text-lg leading-relaxed text-white/80">New to the game or ready to sharpen your skills? Come experience a session and find your rhythm.</p><div className="mt-7"><ButtonLink href="/trial" lime>BOOK YOUR FREE TRIAL</ButtonLink></div><ol className="mt-8 flex flex-col gap-3 border-t border-white/30 pt-5 text-xs"><li><b className="mr-3 text-[#D6FF3F]">01</b>Meet the coach</li><li><b className="mr-3 text-[#D6FF3F]">02</b>Try a guided session</li><li><b className="mr-3 text-[#D6FF3F]">03</b>Find the right training group</li></ol></div></div></section>
      <section className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><Label>TRAINING METHOD</Label><div className="grid gap-16 lg:grid-cols-[0.7fr_1.3fr]"><h2 className="text-6xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-8xl">Built on<br /><span className="text-[#244BFF]">the details.</span></h2><div className="grid grid-cols-1 border-t border-[#111214]/20 sm:grid-cols-2">{principles.map(([n, title, copy]) => <div key={title} className="min-h-48 border-b border-[#111214]/20 py-7 sm:border-r sm:px-7"><span className="text-xs font-bold text-[#244BFF]">{n}</span><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-[#666]">{copy}</p></div>)}</div></div></div></section>
      <section className="bg-[#111214] text-[#F5F4EF] lg:grid lg:grid-cols-2"><div className="relative min-h-[420px] lg:min-h-[680px]"><Image src="/images/spinpoint-facility.png" alt="Modern table tennis academy training space" fill className="object-cover" /></div><div className="flex flex-col justify-center px-5 py-20 lg:px-16"><Label light>THE SPACE</Label><h2 className="max-w-lg text-6xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-8xl">Room to<br /><span className="text-[#D6FF3F]">raise your game.</span></h2><p className="mt-8 max-w-lg text-base leading-relaxed text-[#A4A6AA]">A focused practice environment changes the way you train. Picture clean lines, purposeful repetition and enough room to stay with the ball.</p><ul className="mt-10 max-w-lg border-t border-white/20">{['Table tennis practice tables', 'Training and warm-up area', 'Practice sessions and match-play setup', 'Equipment guidance for new players'].map((item) => <li key={item} className="flex items-center gap-4 border-b border-white/20 py-4 text-sm"><Check className="size-4 text-[#D6FF3F]" />{item}</li>)}</ul><p className="mt-6 text-[10px] uppercase tracking-[0.14em] text-[#666]">Illustrative facility details — verify with the academy.</p></div></section>
      <section id="schedule" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Label>SESSION GUIDE</Label><h2 className="text-6xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-8xl">Find a session<br /><span className="text-[#244BFF]">that fits.</span></h2></div><Link href="/trial" className="group flex items-center gap-3 text-xs font-black tracking-[0.15em]">ENQUIRE ABOUT TIMINGS <ArrowRight className="size-4" /></Link></div><div className="mt-16 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left"><thead><tr className="border-b-2 border-[#111214] text-[10px] tracking-[0.18em] text-[#666]"><th className="pb-4">SESSION TYPE</th><th className="pb-4">DAYS</th><th className="pb-4">TIME WINDOW</th><th className="pb-4">LEVEL</th></tr></thead><tbody>{schedule.map((row) => <tr key={row[0]} className="border-b border-[#111214]/20"><td className="py-6 text-lg font-black">{row[0]}</td><td className="py-6 text-sm text-[#666]">{row[1]}</td><td className="py-6 text-sm text-[#666]">{row[2]}</td><td className="py-6 text-sm text-[#666]">{row[3]}</td></tr>)}</tbody></table></div><p className="mt-5 text-[10px] uppercase tracking-[0.14em] text-[#888]">Illustrative sample schedule — not confirmed live availability.</p></div></section>
      <section className="bg-[#D6FF3F] px-5 py-24 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px] grid gap-10 lg:grid-cols-[0.55fr_1fr] lg:items-center"><h2 className="text-6xl font-black uppercase leading-[0.86] tracking-[-0.07em] sm:text-8xl">The work<br />behind<br /><span className="text-[#244BFF]">every point.</span></h2><div><div className="relative min-h-[320px] sm:min-h-[470px]"><Image src="/images/spinpoint-training.png" alt="Players practicing together in a table tennis club" fill className="object-cover grayscale" /></div><p className="mt-8 max-w-lg text-lg leading-relaxed">Warm up together, stay with the rally, learn from the miss and leave with one more thing to try next time.</p></div></div></section>
      <section className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[0.65fr_1.35fr]"><div><Label>QUICK ANSWERS</Label><h2 className="text-6xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-8xl">Questions<br /><span className="text-[#244BFF]">welcome.</span></h2></div><div className="border-t border-[#111214]/20">{[['Can beginners join?', 'Yes. The academy concept welcomes complete beginners. The right group would be discussed after enquiry.'], ['What should I bring?', 'Comfortable sports clothing and clean indoor shoes are a good start. Equipment details would be confirmed before your session.'], ['How do I book a trial?', 'Use the trial form and share a little about the player. The academy would contact you to discuss a suitable session.'], ['Can I enquire about private coaching?', 'Yes — mention private coaching in your enquiry and the academy can share current options.']].map(([question, answer]) => <details key={question} className="group border-b border-[#111214]/20 py-5"><summary className="flex cursor-pointer list-none items-center justify-between text-lg font-black">{question}<span className="text-2xl transition-transform group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-4 text-sm leading-relaxed text-[#666]">{answer}</p></details>)}</div></div></section>
      <section id="contact" className="bg-[#111214] px-5 py-24 text-[#F5F4EF] lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.2fr_0.8fr] lg:items-end"><div><Label light>READY / SET / SPIN</Label><h2 className="max-w-4xl text-6xl font-black uppercase leading-[0.83] tracking-[-0.07em] sm:text-8xl lg:text-[120px]">Ready to play<br />your <span className="text-[#D6FF3F]">next point?</span></h2></div><div><p className="max-w-sm text-lg leading-relaxed text-[#A4A6AA]">Start with a conversation. Find the session, group or coaching path that feels right.</p><div className="mt-7"><ButtonLink href="/trial" lime>BOOK A FREE TRIAL</ButtonLink></div></div></div></section>
    </main><footer className="bg-[#111214] px-5 pb-8 text-[#F5F4EF] lg:px-10"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 border-t border-white/15 pt-8 md:flex-row md:items-end"><div><Link href="#top" className="flex items-center gap-3"><Mark dark /><span className="text-2xl font-black tracking-[-0.06em]">SPINPOINT</span></Link><p className="mt-3 text-[10px] tracking-[0.2em] text-[#A4A6AA]">TABLE TENNIS ACADEMY / FIND YOUR EDGE.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-[10px] font-bold tracking-[0.15em] text-[#A4A6AA]"><Link href="#academy">ACADEMY</Link><Link href="#programs">PROGRAMS</Link><Link href="#schedule">SCHEDULE</Link><Link href="/trial">TRIAL</Link></div><p className="text-[10px] text-[#666]">Illustrative academy concept by NPN Tech.</p></div></footer>
  </div>
}
